In [15]:


# ////////////////////////////////////////////////////////////////
# // 1.  Import packages that we might need:
# // Packages for data manipulation
import numpy as np
import pandas as pd
# // Web scraping: 
import requests
from bs4 import BeautifulSoup
# // OS. Sometimes need this for finding working directory:
import os
# ////////////////////////////////////////////////////////////////
# ////////////////////////////////////////////////////////////////

# ////////////////////////////////////////////////////////////////
# /// 2.  Set the URL ////////////////////////////////////////////
# This URL finds properties in and around Bristol

URL = "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION%5E219&maxPrice=1500000&radius=5.0&propertyTypes=&includeSSTC=false&mustHave=&dontShow=&furnishTypes=&keywords="

# /// Do the html request:
html = requests.get(URL)
soup = BeautifulSoup(html.content, 'html.parser')


soup_h2=soup.find_all("h2")
#soup_h2

bedrooms=soup.find_all("h2", class_="propertyCard-title")
#bedrooms

prices = soup.find_all("div", class_="propertyCard-priceValue")
#prices

data = [bedrooms, prices]
#data

# // To get the length of our results:
length = len(bedrooms)
#print(length)

prices_list = []

for i in range(length):
  prices_list.append(prices[i].text)

#print(prices_list)

for i in range(length):
  prices_list[i] = prices_list[i].replace(" ", "")
  prices_list[i] = prices_list[i].replace(",", "")
  prices_list[i] = prices_list[i].replace("Â£","")

bedroomsD = np.empty(length, dtype='S80')
# // To get some results:
for i in range(0, length):
   bedroomsD[i] = bedrooms[i].text

#print(bedroomsD)

values = []
for i in range(length): 
  values.append([int(x) for x in bedroomsD[i].split() if x.isdigit()])

#print(values)
# Now we have a list of numbers of bedrooms, without all the text, lets call it bedrooms
bedrooms = values

df = pd.DataFrame(bedrooms)
df.columns = ['Bedrooms']
df['Price'] = prices_list

df = df[df.Price != "POA"]

df= df.dropna()
df['Bedrooms'] = df['Bedrooms'].astype(int)
# We now have a clean list of number of bedrooms on offer and the price of the property. Great. We can plot these against eachother. You could run this for a few different locations or search parameters.
df.to_csv("hw7_bristol.csv",encoding = 'utf-8', index=False)

In [18]:
# Import packages
import numpy as np
import pandas as pd
# // Web scraping: 
import requests
from bs4 import BeautifulSoup
# // OS. Sometimes need this for finding working directory:
import os
# This URL finds properties in and around Bristol

URL = "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION%5E219&maxPrice=1500000&radius=5.0&propertyTypes=&includeSSTC=false&mustHave=&dontShow=&furnishTypes=&keywords="

# /// Do the html request:
html = requests.get(URL)
soup = BeautifulSoup(html.content, 'html.parser')

In [20]:
soup_h2=soup.find_all("h2")
soup_h2

[<h2 class="propertyCard-title" itemprop="name">
             2 bedroom apartment for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             6 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             3 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             7 bedroom end of terrace house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             6 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             Property for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             4 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             6 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             4 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             7 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             6 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             4 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom country house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             8 bedroom apartment for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             3 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom end of terrace house for sale        </h2>,
 <h2 class="mortgage-intro">
         Check your affordability and learn how much you can borrow, based on your monthly income and outgoings.
     </h2>]

In [30]:
bedroom=soup.find_all("h2", class_="propertyCard-title")
bedroom

[<h2 class="propertyCard-title" itemprop="name">
             2 bedroom apartment for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             6 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             3 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             7 bedroom end of terrace house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             6 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             Property for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             4 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             6 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             4 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             7 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             6 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom semi-detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             4 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom country house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             8 bedroom apartment for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             3 bedroom detached house for sale        </h2>,
 <h2 class="propertyCard-title" itemprop="name">
             5 bedroom end of terrace house for sale        </h2>]

In [22]:
prices = soup.find_all("div", class_="propertyCard-priceValue")
prices

[<div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£285,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,500,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">POA        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,495,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,495,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,495,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,475,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,450,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,400,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,350,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,350,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,300,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,300,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,260,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,250,000        </div>,
 <div class="propertyCard-priceValue" data-bind="text: price.displayPrices()[0] ? price.displayPrices()[0].displayPrice : ''">Â£1,250,000        </div>]

In [31]:
data = [bedroom, prices]

# To get the length of our results:
length = len(bedroom)
print(length)

prices_list = []

for i in range(length):
  prices_list.append(prices[i].text)

print(prices_list)

for i in range(length):
  prices_list[i] = prices_list[i].replace(" ", "")
  prices_list[i] = prices_list[i].replace(",", "")
  prices_list[i] = prices_list[i].replace("Â£","")

print(prices_list)

25
['Â£285,000        ', 'Â£1,500,000        ', 'Â£1,500,000        ', 'Â£1,500,000        ', 'Â£1,500,000        ', 'Â£1,500,000        ', 'Â£1,500,000        ', 'Â£1,500,000        ', 'Â£1,500,000        ', 'Â£1,500,000        ', 'Â£1,500,000        ', 'POA        ', 'Â£1,495,000        ', 'Â£1,495,000        ', 'Â£1,495,000        ', 'Â£1,475,000        ', 'Â£1,450,000        ', 'Â£1,400,000        ', 'Â£1,350,000        ', 'Â£1,350,000        ', 'Â£1,300,000        ', 'Â£1,300,000        ', 'Â£1,260,000        ', 'Â£1,250,000        ', 'Â£1,250,000        ']
['285000', '1500000', '1500000', '1500000', '1500000', '1500000', '1500000', '1500000', '1500000', '1500000', '1500000', 'POA', '1495000', '1495000', '1495000', '1475000', '1450000', '1400000', '1350000', '1350000', '1300000', '1300000', '1260000', '1250000', '1250000']

In [32]:
bedroomsD = np.empty(length, dtype='S80')
# To get some results:
for i in range(0, length):
   bedroomsD[i] = bedroom[i].text

print(bedroomsD)

# We can see bedrooms is all of the text in the property descriptions, only part of which (sometimes) contains the number of bedrooms. 
# Values will contain just the integer in this string of text.

values = []
for i in range(length): 
  values.append([int(x) for x in bedroomsD[i].split() if x.isdigit()])

print(values)
# Now we have a list of numbers of bedrooms, without all the text, lets call it bedrooms
bedrooms = values

[b'\n            2 bedroom apartment for sale        '
 b'\n            6 bedroom semi-detached house for sale        '
 b'\n            3 bedroom semi-detached house for sale        '
 b'\n            7 bedroom end of terrace house for sale        '
 b'\n            5 bedroom detached house for sale        '
 b'\n            5 bedroom detached house for sale        '
 b'\n            6 bedroom semi-detached house for sale        '
 b'\n            Property for sale        '
 b'\n            5 bedroom detached house for sale        '
 b'\n            4 bedroom detached house for sale        '
 b'\n            6 bedroom detached house for sale        '
 b'\n            4 bedroom detached house for sale        '
 b'\n            7 bedroom semi-detached house for sale        '
 b'\n            5 bedroom detached house for sale        '
 b'\n            6 bedroom detached house for sale        '
 b'\n            5 bedroom semi-detached house for sale        '
 b'\n            5 bedroom semi-detached house for sale        '
 b'\n            4 bedroom detached house for sale        '
 b'\n            5 bedroom detached house for sale        '
 b'\n            5 bedroom detached house for sale        '
 b'\n            5 bedroom country house for sale        '
 b'\n            5 bedroom detached house for sale        '
 b'\n            8 bedroom apartment for sale        '
 b'\n            3 bedroom detached house for sale        '
 b'\n            5 bedroom end of terrace house for sale        ']
[[2], [6], [3], [7], [5], [5], [6], [], [5], [4], [6], [4], [7], [5], [6], [5], [5], [4], [5], [5], [5], [5], [8], [3], [5]]

In [34]:
# Creating data frame and some cleaning.

df = pd.DataFrame(bedrooms)
df.columns = ['Bedrooms']
df['Price'] = prices_list

df = df[df.Price != "POA"]

df= df.dropna()
df['Bedrooms'] = df['Bedrooms'].astype(int)
# We now have a clean list of number of bedrooms on offer and the price of the property. Great. We can plot these against eachother. You could run this for a few different locations or search parameters.
df.to_csv("hw7_bristol.csv",encoding = 'utf-8', index=False)

In [35]:
df

    Bedrooms    Price
0          2   285000
1          6  1500000
2          3  1500000
3          7  1500000
4          5  1500000
5          5  1500000
6          6  1500000
8          5  1500000
9          4  1500000
10         6  1500000
12         7  1495000
13         5  1495000
14         6  1495000
15         5  1475000
16         5  1450000
17         4  1400000
18         5  1350000
19         5  1350000
20         5  1300000
21         5  1300000
22         8  1260000
23         3  1250000
24         5  1250000